name: Mypy Type Check

on: [push, pull_request]

jobs:
  mypy-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy
    - name: Run mypy
      run: |
        mypy .